server:
  port: 8999

spring:
  application:
    name: api-gateway
  cloud:
    gateway: 
      routes: 
        - id: user-service
          uri: lb://user-service
          predicates: 
            - Path=/user/**,/test/**
            
        - id: contact-service
          uri: lb://contact-service
          predicates: 
            - Path=/contact/**
eureka:
  instance:
    hostname: localhost
    
